name: Arik1
on: push

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar
        uses: actions/checkout@v5

      - name: Instalar
        run: pip install pytest

      - name: Ejecutar
        run: pytest test.py
        
